from . import boq_project
from . import boq_activity
from . import boq_subactivity
from . import boq_cost_type
from . import boq_payment_certificate
from . import boq_variation
from . import crm_lead
from . import sale_order
from . import purchase_order